### PR TITLE
Resolve remaining issues raised during last call

### PR DESCRIPTION
**Pull request by dpk**

### CODE REVIEW

**Comment by dpk** [comment]
Wait, don’t merge this yet. I changed the semantics of sum comparators because, while writing the procedure-by-procedure description which Shiro requested, I thought the new ones were better. Now I’m not sure.

**Comment by dpk** [comment]
Okay, I think the new ones are more intuitive, but also formally completely wrong. (The intention was to do the right thing is if a value matches the type test of more than one of the given comparators, but this actually breaks the ordering semantics.) I need to go back and undo the change in the sample implementation, and also devise a way to describe the ‘old’ behaviour in the bullet point style sensibly

**Comment by dpk** [comment]
Okay, fixed. Ready to go. Hopefully there are no more last call issues …

**Comment by arthurgleckler** [comment]
Thanks.  This is great.

Merged, pushed, and announced.

**Pull request merged**
